config/routes.rb
Rails.application.routes.draw do

  root "registration#login"  # equals to writing [get '/', to: 'registration#login']
  # get 'donx/home'
  # get 'anything',to: 'registration#signup'
  # get '/anything/',to: 'registration#signup'
  get '/about', to: 'donx#about'  # and get 'about', to: 'donx#about' are same
  get '/home' , to: 'donx#home'

  get 'registration/login' 
  get 'registration/signup'

  post '/registration', to: 'registration#create'
  # post '/', to: 'registration#create'   you should provide root_path as helper url

end


# when we type just  [get 'registration/login'] the request format is like localhost:3000/registration/login and it automatically directs to registration controller then login action and login action conventionally loads login view.
# when we type [get '/anything/',to: 'registration#signup'] the request format is like localhost:3000/anything and it manually directs to registration controller then login action and login action conventionally loads login view.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donx_controller.rb
class DonxController < ApplicationController
  layout "donx"
  def home
  end


  def about
  end
end

app/controllers/registration_controller.rb
# Proper controller name for login purposes SessionsController
class RegistrationController < ApplicationController
  layout "registration"
  def login
    render layout: 'loginLayout'
    @user = User.all
  end

  def signup

  end

  def create
    @user = User.new(registration_params)
    puts "............................................................"
    u_name = @user.first_name

    if @user.save
      u_id = @user.id.to_s
      new_user = {:username => u_name +"_"+ u_id }
      if @user.update(new_user)
        p @user
      end
      redirect_to registration_login_path
    else
      render :signup, status: :unprocessable_entity
    end
  end


  private
  def registration_params
    params.require(:user).permit(:first_name, :last_name,:email,:division,:status,:username,:password)

  end
end
=begin
Forms allow you to receive data from your users via the webapp and store that information in your database 
and/or send it off for external processing to something like an API.


=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donx_helper.rb
module DonxHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/donx/about.html.erb
<div class="container">

      <h1>About Us</h1><br>
      <p>The Syndicate is a powerful and feared underworld gang, known for their ruthless tactics and extensive criminal empire. Operating in the shadows, they control a wide range of illegal activities, from coconut tree climbing and making distilled alchol and paid assassination. Their members are fiercely loyal and willing to do whatever it takes to protect the interests of the organization. Despite the constant threat of law enforcement and rival gangs, The Syndicate remains a formidable force in the criminal underworld.</p>

      <%= link_to "Home", home_path %>

</div>



<!-- <a href="/">Home</a> -->

app/views/donx/home.html.erb
<div class="container">
	<h1>HOME</h1><br>
    <p>These messages indicate that certain signals are not being handled by the system or program that is generating them. SIGUSR2, SIGUSR1, and SIGHUP are all signals that can be used to control the behavior of a program. In this case, it seems that the program is not able to respond to these signals, so certain functionality (such as restarting or reopening logs) is unavailable.</p>

    <%= link_to "About me", about_url %>

</div>





<!-- <a href="/about">About me</a><br> -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <!-- <a class="navbar-brand" href="#">TheSyndicate</a> -->
    <%= link_to "TheSyndicate", home_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
          <!-- <a class="nav-link" href="#">Home</a> -->
          <%= link_to "Home", home_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="#">Link</a> -->
          <%= link_to "About", about_url, class: 'nav-link' %>
        </li>

<!--         <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> -->
      </ul>

      <ul class="navbar-nav">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
<!--       <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>


 <!-- yield points to the url that we request...if we request localhost:3000/registration/signup then the request maps to the registration controller with signup action then ultimately the signup view template will load in place of hence this acts as a placeholder -->

app/views/layouts/donx.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/layouts/loginLayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- <div class="d-flex justify-content-center"> -->
      <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="d-flex justify-content-center">
               <main>
                 <%= yield %>
               </main>
            </div>
        </div>
      </div>
    <!-- </div> -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="jumbotron">
    <h1 class="display-4">Log in to the Syndicate</h1>
      <main>
        <%= yield %>
      </main>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>